services:
  postgres:
    image: postgres:16
    container_name: fadesol_taskflow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fadesol_taskflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mounim
    ports:
      - "5432:5432"
    volumes:
      - fadesol_postgres_data:/var/lib/postgresql/data

volumes:
  fadesol_postgres_data:
